# Generated by Django 5.2.17 on 2026-09-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Jeans', 'Jeans'), ('Shirt', 'Shirt'), ('T-Shirt', 'T-Shirt'), ('Dress', 'Dress'), ('Jacket', 'Jacket'), ('Pants', 'Pants'), ('Hoodie', 'Hoodie'), ('Sweatshirt', 'Sweatshirt'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
